import logging
import uuid
from typing import Dict, Any, Callable, Optional, List
from datetime import datetime
from sqlalchemy.orm import Session

from app.response.enums import RiskLevel, ResponseMode
from app.security.rbac import Permission

logger = logging.getLogger(__name__)


class ActionDefinition:
    """Definition of an allowlisted response action."""

    def __init__(
        self,
        action_type: str,
        description: str,
        risk_level: RiskLevel,
        required_permission: Permission,
        execution_handler: Callable,
        verification_handler: Optional[Callable] = None,
        supports_dry_run: bool = True,
    ):
        self.action_type = action_type
        self.description = description
        self.risk_level = risk_level
        self.required_permission = required_permission
        self.execution_handler = execution_handler
        self.verification_handler = verification_handler or self._default_verify
        self.supports_dry_run = supports_dry_run

    def _default_verify(self, result: Dict[str, Any], context: Dict[str, Any]) -> bool:
        return result.get("success", False)


# -------------------------------------------------------------
# Safe Action Adapter Implementations (NO shell, NO eval, NO exec)
# -------------------------------------------------------------

def handle_create_incident(db: Session, config: Dict[str, Any], context: Dict[str, Any], mode: ResponseMode) -> Dict[str, Any]:
    """Safe adapter: Creates an Incident for correlated high/critical alerts."""
    from app.models.incident import Incident, IncidentAlert
    from app.models.alert import Alert

    alert_id = context.get("alert_id")
    title = config.get("title") or f"Automated Incident: {context.get('alert_title', 'High Risk Security Event')}"
    severity = config.get("severity") or context.get("severity", "high")
    risk_score = float(context.get("risk_score", 75.0))

    if mode == ResponseMode.DRY_RUN:
        return {
            "success": True,
            "simulated": True,
            "action": "create_incident",
            "predicted_incident": {
                "title": title,
                "severity": severity,
                "risk_score": risk_score,
            },
            "message": "[DRY_RUN] Would create Incident record."
        }

    # Simulation or Authorized Execution creates a structured Incident
    incident_uuid = str(uuid.uuid4())
    inc_code = f"INC-{uuid.uuid4().hex[:8].upper()}"
    new_inc = Incident(
        id=incident_uuid,
        incident_id=inc_code,
        title=title,
        description=f"Auto-generated by playbook response for alert {alert_id or 'N/A'}.",
        severity=severity.lower(),
        status="new",
        risk_score=risk_score,
        created_at=datetime.utcnow(),
        updated_at=datetime.utcnow(),
    )
    db.add(new_inc)
    db.flush()

    if alert_id:
        # Link alert if exists
        alert = db.query(Alert).filter(Alert.id == alert_id).first()
        if alert:
            inc_alert = IncidentAlert(incident_id=new_inc.id, alert_id=alert.id)
            db.add(inc_alert)

    db.commit()
    db.refresh(new_inc)

    return {
        "success": True,
        "action": "create_incident",
        "incident_id": new_inc.incident_id,
        "id": new_inc.id,
        "severity": new_inc.severity,
        "risk_score": new_inc.risk_score,
        "status": new_inc.status,
    }


def verify_create_incident(result: Dict[str, Any], context: Dict[str, Any]) -> bool:
    if result.get("simulated"):
        return True
    return bool(result.get("incident_id") and result.get("success"))


def handle_update_incident(db: Session, config: Dict[str, Any], context: Dict[str, Any], mode: ResponseMode) -> Dict[str, Any]:
    """Safe adapter: Updates status or notes on an existing Incident."""
    from app.models.incident import Incident

    incident_id = context.get("incident_id") or config.get("incident_id")
    new_status = config.get("status", "investigating")

    if mode == ResponseMode.DRY_RUN:
        return {
            "success": True,
            "simulated": True,
            "action": "update_incident",
            "message": f"[DRY_RUN] Would update incident {incident_id} status to {new_status}"
        }

    if not incident_id:
        return {"success": False, "error": "No incident_id specified for update_incident action."}

    inc = db.query(Incident).filter((Incident.id == incident_id) | (Incident.incident_id == incident_id)).first()
    if not inc:
        return {"success": False, "error": f"Incident {incident_id} not found."}

    inc.status = new_status
    inc.updated_at = datetime.utcnow()
    db.commit()
    db.refresh(inc)

    return {
        "success": True,
        "action": "update_incident",
        "incident_id": inc.incident_id,
        "new_status": inc.status,
    }


def handle_notify_security_team(db: Session, config: Dict[str, Any], context: Dict[str, Any], mode: ResponseMode) -> Dict[str, Any]:
    """Safe adapter: Formats and records a security team notification."""
    channel = config.get("channel", "soc-alerts-internal")
    message = config.get("message") or f"Alert notification: {context.get('alert_title', 'Playbook Triggered')} (Risk: {context.get('risk_score', 'N/A')})"

    logger.info(f"[RESPONSE NOTIFY] Channel: {channel} | Message: {message} | Mode: {mode}")

    return {
        "success": True,
        "action": "notify_security_team",
        "channel": channel,
        "delivered_at": datetime.utcnow().isoformat(),
        "simulated": mode in [ResponseMode.DRY_RUN, ResponseMode.SIMULATION],
        "message": message,
    }


def handle_enrich_event(db: Session, config: Dict[str, Any], context: Dict[str, Any], mode: ResponseMode) -> Dict[str, Any]:
    """Safe adapter: Enriches event details with simulated reputation and geolocation context."""
    source_ip = context.get("source_ip") or config.get("target_ip", "192.168.1.100")
    
    # Safe deterministic threat enrichment metadata
    is_private = source_ip.startswith("10.") or source_ip.startswith("192.168.") or source_ip.startswith("172.16.")
    enrichment_data = {
        "target_ip": source_ip,
        "ip_type": "private_rfc1918" if is_private else "public_routable",
        "threat_reputation_score": 15.0 if is_private else 85.0,
        "enrichment_source": "internal_telemetry_intel",
        "autonomous_system": "AS-INTERNAL" if is_private else "AS-EXTERNAL-THREAT",
        "enriched_at": datetime.utcnow().isoformat(),
    }

    return {
        "success": True,
        "action": "enrich_event",
        "enrichment": enrichment_data,
        "simulated": True,
    }


def handle_quarantine_simulation(db: Session, config: Dict[str, Any], context: Dict[str, Any], mode: ResponseMode) -> Dict[str, Any]:
    """Safe simulation adapter: Simulates host or container quarantine without executing system commands."""
    target_host = config.get("target_host") or context.get("observer_host") or "host-workstation-alpha"
    isolation_vlan = config.get("isolation_vlan", "VLAN-999-QUARANTINE")

    logger.info(f"[SAFE SIMULATION] Host quarantine simulated for {target_host} to {isolation_vlan} (Mode: {mode})")

    return {
        "success": True,
        "action": "quarantine_simulation",
        "simulated": True,
        "target_host": target_host,
        "isolation_vlan": isolation_vlan,
        "simulated_policy_applied": "DROP_INBOUND_EXCEPT_SOC_MANAGEMENT",
        "timestamp": datetime.utcnow().isoformat(),
    }


def handle_account_lock_simulation(db: Session, config: Dict[str, Any], context: Dict[str, Any], mode: ResponseMode) -> Dict[str, Any]:
    """Safe simulation adapter: Simulates locking a compromised user account."""
    target_user = config.get("target_user") or context.get("source_user") or "compromised_user_demo"
    lock_reason = config.get("reason", "Automated Playbook Response - Suspicious Behavioral Anomaly")

    logger.info(f"[SAFE SIMULATION] Account lock simulated for user '{target_user}'. Reason: {lock_reason}")

    return {
        "success": True,
        "action": "account_lock_simulation",
        "simulated": True,
        "target_user": target_user,
        "session_revocation_simulated": True,
        "mfa_reset_required": True,
        "reason": lock_reason,
        "timestamp": datetime.utcnow().isoformat(),
    }


def handle_network_block_simulation(db: Session, config: Dict[str, Any], context: Dict[str, Any], mode: ResponseMode) -> Dict[str, Any]:
    """Safe simulation adapter: Simulates firewall ingress/egress blocking on a malicious IP."""
    target_ip = config.get("target_ip") or context.get("source_ip") or "198.51.100.42"
    block_duration_minutes = int(config.get("duration_minutes", 60))

    logger.info(f"[SAFE SIMULATION] Network firewall block simulated for IP {target_ip} for {block_duration_minutes}m")

    return {
        "success": True,
        "action": "network_block_simulation",
        "simulated": True,
        "target_ip": target_ip,
        "firewall_rule_name": f"AUTO-BLOCK-{target_ip.replace('.', '-')}",
        "duration_minutes": block_duration_minutes,
        "direction": "INGRESS_AND_EGRESS",
        "timestamp": datetime.utcnow().isoformat(),
    }


# -------------------------------------------------------------
# Action Registry
# -------------------------------------------------------------

class ActionRegistry:
    """Centralized, strictly allowlisted action registry."""

    def __init__(self):
        self._registry: Dict[str, ActionDefinition] = {}
        self._register_default_actions()

    def _register_default_actions(self):
        self.register(
            ActionDefinition(
                action_type="create_incident",
                description="Creates an Incident for investigation from an Alert.",
                risk_level=RiskLevel.LOW,
                required_permission=Permission.INCIDENTS_CREATE,
                execution_handler=handle_create_incident,
                verification_handler=verify_create_incident,
                supports_dry_run=True,
            )
        )
        self.register(
            ActionDefinition(
                action_type="update_incident",
                description="Updates the status or details of an existing Incident.",
                risk_level=RiskLevel.LOW,
                required_permission=Permission.INCIDENTS_UPDATE,
                execution_handler=handle_update_incident,
                supports_dry_run=True,
            )
        )
        self.register(
            ActionDefinition(
                action_type="notify_security_team",
                description="Sends an alert notification to the SOC security team.",
                risk_level=RiskLevel.LOW,
                required_permission=Permission.RESPONSES_EXECUTE,
                execution_handler=handle_notify_security_team,
                supports_dry_run=True,
            )
        )
        self.register(
            ActionDefinition(
                action_type="enrich_event",
                description="Enriches event telemetry with threat intelligence and geo data.",
                risk_level=RiskLevel.LOW,
                required_permission=Permission.RESPONSES_EXECUTE,
                execution_handler=handle_enrich_event,
                supports_dry_run=True,
            )
        )
        self.register(
            ActionDefinition(
                action_type="quarantine_simulation",
                description="Simulates host or container network isolation.",
                risk_level=RiskLevel.HIGH,
                required_permission=Permission.RESPONSES_EXECUTE,
                execution_handler=handle_quarantine_simulation,
                supports_dry_run=True,
            )
        )
        self.register(
            ActionDefinition(
                action_type="account_lock_simulation",
                description="Simulates locking a compromised user account and terminating active sessions.",
                risk_level=RiskLevel.HIGH,
                required_permission=Permission.RESPONSES_EXECUTE,
                execution_handler=handle_account_lock_simulation,
                supports_dry_run=True,
            )
        )
        self.register(
            ActionDefinition(
                action_type="network_block_simulation",
                description="Simulates blocking an offending IP address on boundary firewalls.",
                risk_level=RiskLevel.CRITICAL,
                required_permission=Permission.RESPONSES_EXECUTE,
                execution_handler=handle_network_block_simulation,
                supports_dry_run=True,
            )
        )

    def register(self, action_def: ActionDefinition):
        self._registry[action_def.action_type] = action_def

    def get(self, action_type: str) -> Optional[ActionDefinition]:
        return self._registry.get(action_type)

    def is_registered(self, action_type: str) -> bool:
        return action_type in self._registry

    def list_actions(self) -> List[Dict[str, Any]]:
        return [
            {
                "action_type": a.action_type,
                "description": a.description,
                "risk_level": a.risk_level.value,
                "required_permission": a.required_permission.value,
                "supports_dry_run": a.supports_dry_run,
            }
            for a in self._registry.values()
        ]


action_registry = ActionRegistry()
