import logging
from typing import Optional, Dict, Any
from datetime import datetime, timedelta
from redis import Redis
from app.config import settings

logger = logging.getLogger(__name__)


class LoopPreventionGuard:
    """Multi-signal guard preventing response loops, duplicate concurrent executions, and cooldown violations."""

    MAX_EXECUTION_DEPTH = 3

    def __init__(self):
        self._local_cooldowns: Dict[str, datetime] = {}
        self._redis_client: Optional[Redis] = None
        self._redis_available: Optional[bool] = None

    def _get_redis_client(self) -> Optional[Redis]:
        if self._redis_available is False:
            return None
        if self._redis_client is not None:
            return self._redis_client
        try:
            r = Redis.from_url(
                settings.get_redis_url(),
                decode_responses=True,
                socket_connect_timeout=0.2,
                socket_timeout=0.2,
            )
            r.ping()
            self._redis_client = r
            self._redis_available = True
            return self._redis_client
        except Exception:
            self._redis_available = False
            return None

    def is_loop_detected(self, context: Dict[str, Any], current_depth: int = 1) -> bool:
        """Check if event was generated by a prior response action or exceeds recursion depth."""
        # 1. Depth check
        if current_depth > self.MAX_EXECUTION_DEPTH:
            logger.warning(f"[LOOP GUARD] Execution depth {current_depth} exceeded MAX_DEPTH {self.MAX_EXECUTION_DEPTH}")
            return True

        # 2. Provenance check: If event contains response_generated tag
        event_details = context.get("event_details") or {}
        if isinstance(event_details, dict) and event_details.get("response_generated"):
            logger.warning("[LOOP GUARD] Event origin is response_generated; suppressing automated loop.")
            return True

        return False

    def acquire_execution_lock(
        self,
        playbook_id: str,
        entity_key: str,
        cooldown_seconds: int = 300,
    ) -> bool:
        """Acquires a distributed cooldown lock in Redis (with in-memory fallback) for a playbook and target entity."""
        lock_key = f"cyberguard:playbook:lock:{playbook_id}:{entity_key}"
        
        # 1. Try Redis distributed lock
        r = self._get_redis_client()
        if r:
            try:
                # SET lock_key with NX (not exists) and EX (expire)
                acquired = bool(r.set(lock_key, "locked", nx=True, ex=max(1, cooldown_seconds)))
                if not acquired:
                    logger.info(f"[LOOP GUARD] Playbook {playbook_id} on entity {entity_key} suppressed by active Redis cooldown.")
                return acquired
            except Exception as e:
                logger.warning(f"[LOOP GUARD] Redis lock error ({e}), falling back to in-memory store.")

        # 2. In-memory fallback
        now = datetime.utcnow()
        if lock_key in self._local_cooldowns:
            expiry = self._local_cooldowns[lock_key]
            if now < expiry:
                logger.info(f"[LOOP GUARD] Playbook {playbook_id} suppressed by active in-memory cooldown.")
                return False

        self._local_cooldowns[lock_key] = now + timedelta(seconds=cooldown_seconds)
        return True

    def release_execution_lock(self, playbook_id: str, entity_key: str):
        """Releases the lock prematurely if execution failed or was rejected."""
        lock_key = f"cyberguard:playbook:lock:{playbook_id}:{entity_key}"
        r = self._get_redis_client()
        if r:
            try:
                r.delete(lock_key)
            except Exception:
                pass
        self._local_cooldowns.pop(lock_key, None)


loop_guard = LoopPreventionGuard()
