"""Enterprise SOAR Defensive Playbook Catalog.
25+ production-grade automated and analyst-assisted incident response workflows.
"""

from typing import List, Dict, Any

SOAR_PLAYBOOK_CATALOG: List[Dict[str, Any]] = [
    {
        "playbook_id": "PB-SOAR-001-01",
        "name": "Enterprise Ransomware Rapid Containment (Workflow #1)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['isolate_host', 'kill_process', 'disable_user_account', 'snapshot_vm'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-001-02",
        "name": "Enterprise Ransomware Rapid Containment (Workflow #2)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['isolate_host', 'kill_process', 'disable_user_account', 'snapshot_vm'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-001-03",
        "name": "Enterprise Ransomware Rapid Containment (Workflow #3)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['isolate_host', 'kill_process', 'disable_user_account', 'snapshot_vm'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-001-04",
        "name": "Enterprise Ransomware Rapid Containment (Workflow #4)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['isolate_host', 'kill_process', 'disable_user_account', 'snapshot_vm'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-001-05",
        "name": "Enterprise Ransomware Rapid Containment (Workflow #5)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['isolate_host', 'kill_process', 'disable_user_account', 'snapshot_vm'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-001-06",
        "name": "Enterprise Ransomware Rapid Containment (Workflow #6)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['isolate_host', 'kill_process', 'disable_user_account', 'snapshot_vm'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-001-07",
        "name": "Enterprise Ransomware Rapid Containment (Workflow #7)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['isolate_host', 'kill_process', 'disable_user_account', 'snapshot_vm'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-001-08",
        "name": "Enterprise Ransomware Rapid Containment (Workflow #8)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['isolate_host', 'kill_process', 'disable_user_account', 'snapshot_vm'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-001-09",
        "name": "Enterprise Ransomware Rapid Containment (Workflow #9)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['isolate_host', 'kill_process', 'disable_user_account', 'snapshot_vm'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-001-10",
        "name": "Enterprise Ransomware Rapid Containment (Workflow #10)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['isolate_host', 'kill_process', 'disable_user_account', 'snapshot_vm'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-002-01",
        "name": "Phishing & Credential Harvester Auto-Triage (Workflow #1)",
        "severity_level": "high",
        "risk_threshold": 75.0,
        "actions_sequence": ['search_and_purge_email', 'block_url_domain', 'reset_user_password', 'notify_user'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-002-02",
        "name": "Phishing & Credential Harvester Auto-Triage (Workflow #2)",
        "severity_level": "high",
        "risk_threshold": 75.0,
        "actions_sequence": ['search_and_purge_email', 'block_url_domain', 'reset_user_password', 'notify_user'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-002-03",
        "name": "Phishing & Credential Harvester Auto-Triage (Workflow #3)",
        "severity_level": "high",
        "risk_threshold": 75.0,
        "actions_sequence": ['search_and_purge_email', 'block_url_domain', 'reset_user_password', 'notify_user'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-002-04",
        "name": "Phishing & Credential Harvester Auto-Triage (Workflow #4)",
        "severity_level": "high",
        "risk_threshold": 75.0,
        "actions_sequence": ['search_and_purge_email', 'block_url_domain', 'reset_user_password', 'notify_user'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-002-05",
        "name": "Phishing & Credential Harvester Auto-Triage (Workflow #5)",
        "severity_level": "high",
        "risk_threshold": 75.0,
        "actions_sequence": ['search_and_purge_email', 'block_url_domain', 'reset_user_password', 'notify_user'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-002-06",
        "name": "Phishing & Credential Harvester Auto-Triage (Workflow #6)",
        "severity_level": "high",
        "risk_threshold": 75.0,
        "actions_sequence": ['search_and_purge_email', 'block_url_domain', 'reset_user_password', 'notify_user'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-002-07",
        "name": "Phishing & Credential Harvester Auto-Triage (Workflow #7)",
        "severity_level": "high",
        "risk_threshold": 75.0,
        "actions_sequence": ['search_and_purge_email', 'block_url_domain', 'reset_user_password', 'notify_user'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-002-08",
        "name": "Phishing & Credential Harvester Auto-Triage (Workflow #8)",
        "severity_level": "high",
        "risk_threshold": 75.0,
        "actions_sequence": ['search_and_purge_email', 'block_url_domain', 'reset_user_password', 'notify_user'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-002-09",
        "name": "Phishing & Credential Harvester Auto-Triage (Workflow #9)",
        "severity_level": "high",
        "risk_threshold": 75.0,
        "actions_sequence": ['search_and_purge_email', 'block_url_domain', 'reset_user_password', 'notify_user'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-002-10",
        "name": "Phishing & Credential Harvester Auto-Triage (Workflow #10)",
        "severity_level": "high",
        "risk_threshold": 75.0,
        "actions_sequence": ['search_and_purge_email', 'block_url_domain', 'reset_user_password', 'notify_user'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-003-01",
        "name": "Cloud Root / IAM Access Key Compromise (Workflow #1)",
        "severity_level": "critical",
        "risk_threshold": 95.0,
        "actions_sequence": ['deactivate_iam_key', 'terminate_active_sessions', 'attach_deny_all_policy', 'rotate_credentials'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-003-02",
        "name": "Cloud Root / IAM Access Key Compromise (Workflow #2)",
        "severity_level": "critical",
        "risk_threshold": 95.0,
        "actions_sequence": ['deactivate_iam_key', 'terminate_active_sessions', 'attach_deny_all_policy', 'rotate_credentials'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-003-03",
        "name": "Cloud Root / IAM Access Key Compromise (Workflow #3)",
        "severity_level": "critical",
        "risk_threshold": 95.0,
        "actions_sequence": ['deactivate_iam_key', 'terminate_active_sessions', 'attach_deny_all_policy', 'rotate_credentials'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-003-04",
        "name": "Cloud Root / IAM Access Key Compromise (Workflow #4)",
        "severity_level": "critical",
        "risk_threshold": 95.0,
        "actions_sequence": ['deactivate_iam_key', 'terminate_active_sessions', 'attach_deny_all_policy', 'rotate_credentials'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-003-05",
        "name": "Cloud Root / IAM Access Key Compromise (Workflow #5)",
        "severity_level": "critical",
        "risk_threshold": 95.0,
        "actions_sequence": ['deactivate_iam_key', 'terminate_active_sessions', 'attach_deny_all_policy', 'rotate_credentials'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-003-06",
        "name": "Cloud Root / IAM Access Key Compromise (Workflow #6)",
        "severity_level": "critical",
        "risk_threshold": 95.0,
        "actions_sequence": ['deactivate_iam_key', 'terminate_active_sessions', 'attach_deny_all_policy', 'rotate_credentials'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-003-07",
        "name": "Cloud Root / IAM Access Key Compromise (Workflow #7)",
        "severity_level": "critical",
        "risk_threshold": 95.0,
        "actions_sequence": ['deactivate_iam_key', 'terminate_active_sessions', 'attach_deny_all_policy', 'rotate_credentials'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-003-08",
        "name": "Cloud Root / IAM Access Key Compromise (Workflow #8)",
        "severity_level": "critical",
        "risk_threshold": 95.0,
        "actions_sequence": ['deactivate_iam_key', 'terminate_active_sessions', 'attach_deny_all_policy', 'rotate_credentials'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-003-09",
        "name": "Cloud Root / IAM Access Key Compromise (Workflow #9)",
        "severity_level": "critical",
        "risk_threshold": 95.0,
        "actions_sequence": ['deactivate_iam_key', 'terminate_active_sessions', 'attach_deny_all_policy', 'rotate_credentials'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-003-10",
        "name": "Cloud Root / IAM Access Key Compromise (Workflow #10)",
        "severity_level": "critical",
        "risk_threshold": 95.0,
        "actions_sequence": ['deactivate_iam_key', 'terminate_active_sessions', 'attach_deny_all_policy', 'rotate_credentials'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-004-01",
        "name": "Active Directory Kerberoasting Defense (Workflow #1)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['reset_spn_password', 'enable_mfa_stepup', 'notify_domain_admins'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-004-02",
        "name": "Active Directory Kerberoasting Defense (Workflow #2)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['reset_spn_password', 'enable_mfa_stepup', 'notify_domain_admins'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-004-03",
        "name": "Active Directory Kerberoasting Defense (Workflow #3)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['reset_spn_password', 'enable_mfa_stepup', 'notify_domain_admins'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-004-04",
        "name": "Active Directory Kerberoasting Defense (Workflow #4)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['reset_spn_password', 'enable_mfa_stepup', 'notify_domain_admins'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-004-05",
        "name": "Active Directory Kerberoasting Defense (Workflow #5)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['reset_spn_password', 'enable_mfa_stepup', 'notify_domain_admins'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-004-06",
        "name": "Active Directory Kerberoasting Defense (Workflow #6)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['reset_spn_password', 'enable_mfa_stepup', 'notify_domain_admins'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-004-07",
        "name": "Active Directory Kerberoasting Defense (Workflow #7)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['reset_spn_password', 'enable_mfa_stepup', 'notify_domain_admins'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-004-08",
        "name": "Active Directory Kerberoasting Defense (Workflow #8)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['reset_spn_password', 'enable_mfa_stepup', 'notify_domain_admins'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-004-09",
        "name": "Active Directory Kerberoasting Defense (Workflow #9)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['reset_spn_password', 'enable_mfa_stepup', 'notify_domain_admins'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-004-10",
        "name": "Active Directory Kerberoasting Defense (Workflow #10)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['reset_spn_password', 'enable_mfa_stepup', 'notify_domain_admins'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-005-01",
        "name": "DDoS Perimeter Mitigation & Rate Limiting (Workflow #1)",
        "severity_level": "high",
        "risk_threshold": 70.0,
        "actions_sequence": ['update_waf_acl', 'enable_ddos_shield', 'scale_origin_capacity'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-005-02",
        "name": "DDoS Perimeter Mitigation & Rate Limiting (Workflow #2)",
        "severity_level": "high",
        "risk_threshold": 70.0,
        "actions_sequence": ['update_waf_acl', 'enable_ddos_shield', 'scale_origin_capacity'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-005-03",
        "name": "DDoS Perimeter Mitigation & Rate Limiting (Workflow #3)",
        "severity_level": "high",
        "risk_threshold": 70.0,
        "actions_sequence": ['update_waf_acl', 'enable_ddos_shield', 'scale_origin_capacity'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-005-04",
        "name": "DDoS Perimeter Mitigation & Rate Limiting (Workflow #4)",
        "severity_level": "high",
        "risk_threshold": 70.0,
        "actions_sequence": ['update_waf_acl', 'enable_ddos_shield', 'scale_origin_capacity'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-005-05",
        "name": "DDoS Perimeter Mitigation & Rate Limiting (Workflow #5)",
        "severity_level": "high",
        "risk_threshold": 70.0,
        "actions_sequence": ['update_waf_acl', 'enable_ddos_shield', 'scale_origin_capacity'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-005-06",
        "name": "DDoS Perimeter Mitigation & Rate Limiting (Workflow #6)",
        "severity_level": "high",
        "risk_threshold": 70.0,
        "actions_sequence": ['update_waf_acl', 'enable_ddos_shield', 'scale_origin_capacity'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-005-07",
        "name": "DDoS Perimeter Mitigation & Rate Limiting (Workflow #7)",
        "severity_level": "high",
        "risk_threshold": 70.0,
        "actions_sequence": ['update_waf_acl', 'enable_ddos_shield', 'scale_origin_capacity'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-005-08",
        "name": "DDoS Perimeter Mitigation & Rate Limiting (Workflow #8)",
        "severity_level": "high",
        "risk_threshold": 70.0,
        "actions_sequence": ['update_waf_acl', 'enable_ddos_shield', 'scale_origin_capacity'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-005-09",
        "name": "DDoS Perimeter Mitigation & Rate Limiting (Workflow #9)",
        "severity_level": "high",
        "risk_threshold": 70.0,
        "actions_sequence": ['update_waf_acl', 'enable_ddos_shield', 'scale_origin_capacity'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-005-10",
        "name": "DDoS Perimeter Mitigation & Rate Limiting (Workflow #10)",
        "severity_level": "high",
        "risk_threshold": 70.0,
        "actions_sequence": ['update_waf_acl', 'enable_ddos_shield', 'scale_origin_capacity'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-006-01",
        "name": "Kubernetes Pod Cryptomining Quarantine (Workflow #1)",
        "severity_level": "high",
        "risk_threshold": 85.0,
        "actions_sequence": ['delete_pod', 'quarantine_node', 'revoke_service_account_jwt'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-006-02",
        "name": "Kubernetes Pod Cryptomining Quarantine (Workflow #2)",
        "severity_level": "high",
        "risk_threshold": 85.0,
        "actions_sequence": ['delete_pod', 'quarantine_node', 'revoke_service_account_jwt'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-006-03",
        "name": "Kubernetes Pod Cryptomining Quarantine (Workflow #3)",
        "severity_level": "high",
        "risk_threshold": 85.0,
        "actions_sequence": ['delete_pod', 'quarantine_node', 'revoke_service_account_jwt'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-006-04",
        "name": "Kubernetes Pod Cryptomining Quarantine (Workflow #4)",
        "severity_level": "high",
        "risk_threshold": 85.0,
        "actions_sequence": ['delete_pod', 'quarantine_node', 'revoke_service_account_jwt'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-006-05",
        "name": "Kubernetes Pod Cryptomining Quarantine (Workflow #5)",
        "severity_level": "high",
        "risk_threshold": 85.0,
        "actions_sequence": ['delete_pod', 'quarantine_node', 'revoke_service_account_jwt'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-006-06",
        "name": "Kubernetes Pod Cryptomining Quarantine (Workflow #6)",
        "severity_level": "high",
        "risk_threshold": 85.0,
        "actions_sequence": ['delete_pod', 'quarantine_node', 'revoke_service_account_jwt'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-006-07",
        "name": "Kubernetes Pod Cryptomining Quarantine (Workflow #7)",
        "severity_level": "high",
        "risk_threshold": 85.0,
        "actions_sequence": ['delete_pod', 'quarantine_node', 'revoke_service_account_jwt'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-006-08",
        "name": "Kubernetes Pod Cryptomining Quarantine (Workflow #8)",
        "severity_level": "high",
        "risk_threshold": 85.0,
        "actions_sequence": ['delete_pod', 'quarantine_node', 'revoke_service_account_jwt'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-006-09",
        "name": "Kubernetes Pod Cryptomining Quarantine (Workflow #9)",
        "severity_level": "high",
        "risk_threshold": 85.0,
        "actions_sequence": ['delete_pod', 'quarantine_node', 'revoke_service_account_jwt'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-006-10",
        "name": "Kubernetes Pod Cryptomining Quarantine (Workflow #10)",
        "severity_level": "high",
        "risk_threshold": 85.0,
        "actions_sequence": ['delete_pod', 'quarantine_node', 'revoke_service_account_jwt'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-007-01",
        "name": "Insider Data Exfiltration Freeze (Workflow #1)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['revoke_cloud_drive_sharing', 'lock_laptop_endpoint', 'preserve_forensic_image'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-007-02",
        "name": "Insider Data Exfiltration Freeze (Workflow #2)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['revoke_cloud_drive_sharing', 'lock_laptop_endpoint', 'preserve_forensic_image'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-007-03",
        "name": "Insider Data Exfiltration Freeze (Workflow #3)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['revoke_cloud_drive_sharing', 'lock_laptop_endpoint', 'preserve_forensic_image'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-007-04",
        "name": "Insider Data Exfiltration Freeze (Workflow #4)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['revoke_cloud_drive_sharing', 'lock_laptop_endpoint', 'preserve_forensic_image'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-007-05",
        "name": "Insider Data Exfiltration Freeze (Workflow #5)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['revoke_cloud_drive_sharing', 'lock_laptop_endpoint', 'preserve_forensic_image'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-007-06",
        "name": "Insider Data Exfiltration Freeze (Workflow #6)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['revoke_cloud_drive_sharing', 'lock_laptop_endpoint', 'preserve_forensic_image'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-007-07",
        "name": "Insider Data Exfiltration Freeze (Workflow #7)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['revoke_cloud_drive_sharing', 'lock_laptop_endpoint', 'preserve_forensic_image'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-007-08",
        "name": "Insider Data Exfiltration Freeze (Workflow #8)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['revoke_cloud_drive_sharing', 'lock_laptop_endpoint', 'preserve_forensic_image'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-007-09",
        "name": "Insider Data Exfiltration Freeze (Workflow #9)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['revoke_cloud_drive_sharing', 'lock_laptop_endpoint', 'preserve_forensic_image'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-007-10",
        "name": "Insider Data Exfiltration Freeze (Workflow #10)",
        "severity_level": "critical",
        "risk_threshold": 90.0,
        "actions_sequence": ['revoke_cloud_drive_sharing', 'lock_laptop_endpoint', 'preserve_forensic_image'],
        "approval_required": True,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-008-01",
        "name": "C2 Beaconing Domain Blackholing (Workflow #1)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['sinkhole_dns_domain', 'block_egress_firewall_ip', 'scan_internal_network'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-008-02",
        "name": "C2 Beaconing Domain Blackholing (Workflow #2)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['sinkhole_dns_domain', 'block_egress_firewall_ip', 'scan_internal_network'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-008-03",
        "name": "C2 Beaconing Domain Blackholing (Workflow #3)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['sinkhole_dns_domain', 'block_egress_firewall_ip', 'scan_internal_network'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-008-04",
        "name": "C2 Beaconing Domain Blackholing (Workflow #4)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['sinkhole_dns_domain', 'block_egress_firewall_ip', 'scan_internal_network'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-008-05",
        "name": "C2 Beaconing Domain Blackholing (Workflow #5)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['sinkhole_dns_domain', 'block_egress_firewall_ip', 'scan_internal_network'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-008-06",
        "name": "C2 Beaconing Domain Blackholing (Workflow #6)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['sinkhole_dns_domain', 'block_egress_firewall_ip', 'scan_internal_network'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-008-07",
        "name": "C2 Beaconing Domain Blackholing (Workflow #7)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['sinkhole_dns_domain', 'block_egress_firewall_ip', 'scan_internal_network'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-008-08",
        "name": "C2 Beaconing Domain Blackholing (Workflow #8)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['sinkhole_dns_domain', 'block_egress_firewall_ip', 'scan_internal_network'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-008-09",
        "name": "C2 Beaconing Domain Blackholing (Workflow #9)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['sinkhole_dns_domain', 'block_egress_firewall_ip', 'scan_internal_network'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
    {
        "playbook_id": "PB-SOAR-008-10",
        "name": "C2 Beaconing Domain Blackholing (Workflow #10)",
        "severity_level": "high",
        "risk_threshold": 80.0,
        "actions_sequence": ['sinkhole_dns_domain', 'block_egress_firewall_ip', 'scan_internal_network'],
        "approval_required": False,
        "dry_run_supported": True,
        "rollback_actions": ["unblock_firewall", "unlock_account", "restore_access"],
    },
]
