"""Kubernetes and Container Runtime Security Detection Rules Catalog.
Covers pod escapes, host path mounts, privileged container executions, and cluster RBAC tampering.
"""

from typing import List, Dict, Any

CONTAINER_DETECTION_RULES: List[Dict[str, Any]] = [
    {
        "rule_id": "RULE-K8S-0001",
        "title": "K8s Privileged Pod Detection #1",
        "description": "Deploy Container - Privileged Security Context (Variant 1).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0002",
        "title": "K8s Privileged Pod Detection #2",
        "description": "Deploy Container - Privileged Security Context (Variant 2).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0003",
        "title": "K8s Privileged Pod Detection #3",
        "description": "Deploy Container - Privileged Security Context (Variant 3).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0004",
        "title": "K8s Privileged Pod Detection #4",
        "description": "Deploy Container - Privileged Security Context (Variant 4).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0005",
        "title": "K8s Privileged Pod Detection #5",
        "description": "Deploy Container - Privileged Security Context (Variant 5).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0006",
        "title": "K8s Privileged Pod Detection #6",
        "description": "Deploy Container - Privileged Security Context (Variant 6).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0007",
        "title": "K8s Privileged Pod Detection #7",
        "description": "Deploy Container - Privileged Security Context (Variant 7).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0008",
        "title": "K8s Privileged Pod Detection #8",
        "description": "Deploy Container - Privileged Security Context (Variant 8).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0009",
        "title": "K8s Privileged Pod Detection #9",
        "description": "Deploy Container - Privileged Security Context (Variant 9).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0010",
        "title": "K8s Privileged Pod Detection #10",
        "description": "Deploy Container - Privileged Security Context (Variant 10).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0011",
        "title": "K8s Privileged Pod Detection #11",
        "description": "Deploy Container - Privileged Security Context (Variant 11).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0012",
        "title": "K8s Privileged Pod Detection #12",
        "description": "Deploy Container - Privileged Security Context (Variant 12).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0013",
        "title": "K8s Privileged Pod Detection #13",
        "description": "Deploy Container - Privileged Security Context (Variant 13).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0014",
        "title": "K8s Privileged Pod Detection #14",
        "description": "Deploy Container - Privileged Security Context (Variant 14).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0015",
        "title": "K8s Privileged Pod Detection #15",
        "description": "Deploy Container - Privileged Security Context (Variant 15).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0016",
        "title": "K8s Privileged Pod Detection #16",
        "description": "Deploy Container - Privileged Security Context (Variant 16).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0017",
        "title": "K8s Privileged Pod Detection #17",
        "description": "Deploy Container - Privileged Security Context (Variant 17).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0018",
        "title": "K8s Privileged Pod Detection #18",
        "description": "Deploy Container - Privileged Security Context (Variant 18).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0019",
        "title": "K8s Privileged Pod Detection #19",
        "description": "Deploy Container - Privileged Security Context (Variant 19).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0020",
        "title": "K8s Privileged Pod Detection #20",
        "description": "Deploy Container - Privileged Security Context (Variant 20).",
        "mitre_attack_id": "T1610",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0021",
        "title": "K8s Host Path Mount Detection #1",
        "description": "Escape to Host via /var/run/docker.sock (Variant 1).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0022",
        "title": "K8s Host Path Mount Detection #2",
        "description": "Escape to Host via /var/run/docker.sock (Variant 2).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0023",
        "title": "K8s Host Path Mount Detection #3",
        "description": "Escape to Host via /var/run/docker.sock (Variant 3).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0024",
        "title": "K8s Host Path Mount Detection #4",
        "description": "Escape to Host via /var/run/docker.sock (Variant 4).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0025",
        "title": "K8s Host Path Mount Detection #5",
        "description": "Escape to Host via /var/run/docker.sock (Variant 5).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0026",
        "title": "K8s Host Path Mount Detection #6",
        "description": "Escape to Host via /var/run/docker.sock (Variant 6).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0027",
        "title": "K8s Host Path Mount Detection #7",
        "description": "Escape to Host via /var/run/docker.sock (Variant 7).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0028",
        "title": "K8s Host Path Mount Detection #8",
        "description": "Escape to Host via /var/run/docker.sock (Variant 8).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0029",
        "title": "K8s Host Path Mount Detection #9",
        "description": "Escape to Host via /var/run/docker.sock (Variant 9).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0030",
        "title": "K8s Host Path Mount Detection #10",
        "description": "Escape to Host via /var/run/docker.sock (Variant 10).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0031",
        "title": "K8s Host Path Mount Detection #11",
        "description": "Escape to Host via /var/run/docker.sock (Variant 11).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0032",
        "title": "K8s Host Path Mount Detection #12",
        "description": "Escape to Host via /var/run/docker.sock (Variant 12).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0033",
        "title": "K8s Host Path Mount Detection #13",
        "description": "Escape to Host via /var/run/docker.sock (Variant 13).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0034",
        "title": "K8s Host Path Mount Detection #14",
        "description": "Escape to Host via /var/run/docker.sock (Variant 14).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0035",
        "title": "K8s Host Path Mount Detection #15",
        "description": "Escape to Host via /var/run/docker.sock (Variant 15).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0036",
        "title": "K8s Host Path Mount Detection #16",
        "description": "Escape to Host via /var/run/docker.sock (Variant 16).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0037",
        "title": "K8s Host Path Mount Detection #17",
        "description": "Escape to Host via /var/run/docker.sock (Variant 17).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0038",
        "title": "K8s Host Path Mount Detection #18",
        "description": "Escape to Host via /var/run/docker.sock (Variant 18).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0039",
        "title": "K8s Host Path Mount Detection #19",
        "description": "Escape to Host via /var/run/docker.sock (Variant 19).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0040",
        "title": "K8s Host Path Mount Detection #20",
        "description": "Escape to Host via /var/run/docker.sock (Variant 20).",
        "mitre_attack_id": "T1611",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0041",
        "title": "K8s Cluster Admin Binding Detection #1",
        "description": "ClusterRoleBinding to cluster-admin (Variant 1).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0042",
        "title": "K8s Cluster Admin Binding Detection #2",
        "description": "ClusterRoleBinding to cluster-admin (Variant 2).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0043",
        "title": "K8s Cluster Admin Binding Detection #3",
        "description": "ClusterRoleBinding to cluster-admin (Variant 3).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0044",
        "title": "K8s Cluster Admin Binding Detection #4",
        "description": "ClusterRoleBinding to cluster-admin (Variant 4).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0045",
        "title": "K8s Cluster Admin Binding Detection #5",
        "description": "ClusterRoleBinding to cluster-admin (Variant 5).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0046",
        "title": "K8s Cluster Admin Binding Detection #6",
        "description": "ClusterRoleBinding to cluster-admin (Variant 6).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0047",
        "title": "K8s Cluster Admin Binding Detection #7",
        "description": "ClusterRoleBinding to cluster-admin (Variant 7).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0048",
        "title": "K8s Cluster Admin Binding Detection #8",
        "description": "ClusterRoleBinding to cluster-admin (Variant 8).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0049",
        "title": "K8s Cluster Admin Binding Detection #9",
        "description": "ClusterRoleBinding to cluster-admin (Variant 9).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0050",
        "title": "K8s Cluster Admin Binding Detection #10",
        "description": "ClusterRoleBinding to cluster-admin (Variant 10).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0051",
        "title": "K8s Cluster Admin Binding Detection #11",
        "description": "ClusterRoleBinding to cluster-admin (Variant 11).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0052",
        "title": "K8s Cluster Admin Binding Detection #12",
        "description": "ClusterRoleBinding to cluster-admin (Variant 12).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0053",
        "title": "K8s Cluster Admin Binding Detection #13",
        "description": "ClusterRoleBinding to cluster-admin (Variant 13).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0054",
        "title": "K8s Cluster Admin Binding Detection #14",
        "description": "ClusterRoleBinding to cluster-admin (Variant 14).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0055",
        "title": "K8s Cluster Admin Binding Detection #15",
        "description": "ClusterRoleBinding to cluster-admin (Variant 15).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0056",
        "title": "K8s Cluster Admin Binding Detection #16",
        "description": "ClusterRoleBinding to cluster-admin (Variant 16).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0057",
        "title": "K8s Cluster Admin Binding Detection #17",
        "description": "ClusterRoleBinding to cluster-admin (Variant 17).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0058",
        "title": "K8s Cluster Admin Binding Detection #18",
        "description": "ClusterRoleBinding to cluster-admin (Variant 18).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0059",
        "title": "K8s Cluster Admin Binding Detection #19",
        "description": "ClusterRoleBinding to cluster-admin (Variant 19).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0060",
        "title": "K8s Cluster Admin Binding Detection #20",
        "description": "ClusterRoleBinding to cluster-admin (Variant 20).",
        "mitre_attack_id": "T1098",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0061",
        "title": "K8s Kubernetes Exec Detection #1",
        "description": "Exec into Production Pod Container (Variant 1).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0062",
        "title": "K8s Kubernetes Exec Detection #2",
        "description": "Exec into Production Pod Container (Variant 2).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0063",
        "title": "K8s Kubernetes Exec Detection #3",
        "description": "Exec into Production Pod Container (Variant 3).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0064",
        "title": "K8s Kubernetes Exec Detection #4",
        "description": "Exec into Production Pod Container (Variant 4).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0065",
        "title": "K8s Kubernetes Exec Detection #5",
        "description": "Exec into Production Pod Container (Variant 5).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0066",
        "title": "K8s Kubernetes Exec Detection #6",
        "description": "Exec into Production Pod Container (Variant 6).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0067",
        "title": "K8s Kubernetes Exec Detection #7",
        "description": "Exec into Production Pod Container (Variant 7).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0068",
        "title": "K8s Kubernetes Exec Detection #8",
        "description": "Exec into Production Pod Container (Variant 8).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0069",
        "title": "K8s Kubernetes Exec Detection #9",
        "description": "Exec into Production Pod Container (Variant 9).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0070",
        "title": "K8s Kubernetes Exec Detection #10",
        "description": "Exec into Production Pod Container (Variant 10).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0071",
        "title": "K8s Kubernetes Exec Detection #11",
        "description": "Exec into Production Pod Container (Variant 11).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0072",
        "title": "K8s Kubernetes Exec Detection #12",
        "description": "Exec into Production Pod Container (Variant 12).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0073",
        "title": "K8s Kubernetes Exec Detection #13",
        "description": "Exec into Production Pod Container (Variant 13).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0074",
        "title": "K8s Kubernetes Exec Detection #14",
        "description": "Exec into Production Pod Container (Variant 14).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0075",
        "title": "K8s Kubernetes Exec Detection #15",
        "description": "Exec into Production Pod Container (Variant 15).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0076",
        "title": "K8s Kubernetes Exec Detection #16",
        "description": "Exec into Production Pod Container (Variant 16).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0077",
        "title": "K8s Kubernetes Exec Detection #17",
        "description": "Exec into Production Pod Container (Variant 17).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0078",
        "title": "K8s Kubernetes Exec Detection #18",
        "description": "Exec into Production Pod Container (Variant 18).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0079",
        "title": "K8s Kubernetes Exec Detection #19",
        "description": "Exec into Production Pod Container (Variant 19).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0080",
        "title": "K8s Kubernetes Exec Detection #20",
        "description": "Exec into Production Pod Container (Variant 20).",
        "mitre_attack_id": "T1609",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0081",
        "title": "K8s Secrets Dumping Detection #1",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 1).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0082",
        "title": "K8s Secrets Dumping Detection #2",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 2).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0083",
        "title": "K8s Secrets Dumping Detection #3",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 3).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0084",
        "title": "K8s Secrets Dumping Detection #4",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 4).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0085",
        "title": "K8s Secrets Dumping Detection #5",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 5).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0086",
        "title": "K8s Secrets Dumping Detection #6",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 6).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0087",
        "title": "K8s Secrets Dumping Detection #7",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 7).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0088",
        "title": "K8s Secrets Dumping Detection #8",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 8).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0089",
        "title": "K8s Secrets Dumping Detection #9",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 9).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0090",
        "title": "K8s Secrets Dumping Detection #10",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 10).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0091",
        "title": "K8s Secrets Dumping Detection #11",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 11).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0092",
        "title": "K8s Secrets Dumping Detection #12",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 12).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0093",
        "title": "K8s Secrets Dumping Detection #13",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 13).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0094",
        "title": "K8s Secrets Dumping Detection #14",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 14).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0095",
        "title": "K8s Secrets Dumping Detection #15",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 15).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0096",
        "title": "K8s Secrets Dumping Detection #16",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 16).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0097",
        "title": "K8s Secrets Dumping Detection #17",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 17).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0098",
        "title": "K8s Secrets Dumping Detection #18",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 18).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0099",
        "title": "K8s Secrets Dumping Detection #19",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 19).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0100",
        "title": "K8s Secrets Dumping Detection #20",
        "description": "Bulk Read Kubernetes Secret Resources (Variant 20).",
        "mitre_attack_id": "T1552.007",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0101",
        "title": "K8s Node Compromise Detection #1",
        "description": "Kubelet API Unauthorized Access (Variant 1).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0102",
        "title": "K8s Node Compromise Detection #2",
        "description": "Kubelet API Unauthorized Access (Variant 2).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0103",
        "title": "K8s Node Compromise Detection #3",
        "description": "Kubelet API Unauthorized Access (Variant 3).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0104",
        "title": "K8s Node Compromise Detection #4",
        "description": "Kubelet API Unauthorized Access (Variant 4).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0105",
        "title": "K8s Node Compromise Detection #5",
        "description": "Kubelet API Unauthorized Access (Variant 5).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0106",
        "title": "K8s Node Compromise Detection #6",
        "description": "Kubelet API Unauthorized Access (Variant 6).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0107",
        "title": "K8s Node Compromise Detection #7",
        "description": "Kubelet API Unauthorized Access (Variant 7).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0108",
        "title": "K8s Node Compromise Detection #8",
        "description": "Kubelet API Unauthorized Access (Variant 8).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0109",
        "title": "K8s Node Compromise Detection #9",
        "description": "Kubelet API Unauthorized Access (Variant 9).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0110",
        "title": "K8s Node Compromise Detection #10",
        "description": "Kubelet API Unauthorized Access (Variant 10).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0111",
        "title": "K8s Node Compromise Detection #11",
        "description": "Kubelet API Unauthorized Access (Variant 11).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0112",
        "title": "K8s Node Compromise Detection #12",
        "description": "Kubelet API Unauthorized Access (Variant 12).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0113",
        "title": "K8s Node Compromise Detection #13",
        "description": "Kubelet API Unauthorized Access (Variant 13).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0114",
        "title": "K8s Node Compromise Detection #14",
        "description": "Kubelet API Unauthorized Access (Variant 14).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0115",
        "title": "K8s Node Compromise Detection #15",
        "description": "Kubelet API Unauthorized Access (Variant 15).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0116",
        "title": "K8s Node Compromise Detection #16",
        "description": "Kubelet API Unauthorized Access (Variant 16).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0117",
        "title": "K8s Node Compromise Detection #17",
        "description": "Kubelet API Unauthorized Access (Variant 17).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][1],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][1],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0118",
        "title": "K8s Node Compromise Detection #18",
        "description": "Kubelet API Unauthorized Access (Variant 18).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][2],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][2],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0119",
        "title": "K8s Node Compromise Detection #19",
        "description": "Kubelet API Unauthorized Access (Variant 19).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if False else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][3],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][3],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
    {
        "rule_id": "RULE-K8S-0120",
        "title": "K8s Node Compromise Detection #20",
        "description": "Kubelet API Unauthorized Access (Variant 20).",
        "mitre_attack_id": "T1613",
        "severity": "critical" if True else "high",
        "category": "kubernetes_audit",
        "condition": {
            "verb": ['create', 'update', 'patch', 'exec'][0],
            "resource": ['pods', 'secrets', 'clusterrolebindings', 'nodes'][0],
        },
        "tags": ["kubernetes", "containers", "cloud_native"],
        "enabled": True,
    },
]
