"""YARA Malware Identification and Binary Pattern Catalog.
"""

from typing import List, Dict, Any

YARA_RULE_CATALOG: List[Dict[str, Any]] = [
    {
        "yara_rule_name": "CobaltStrike_Beacon_1",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_2",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_3",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_4",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_5",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_6",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_7",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_8",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_9",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_10",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_11",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_12",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_13",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_14",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_15",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_16",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_17",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_18",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_19",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_20",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_21",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_22",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_23",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_24",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "CobaltStrike_Beacon_25",
        "malware_family": "CobaltStrike_Beacon",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_1",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_2",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_3",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_4",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_5",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_6",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_7",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_8",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_9",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_10",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_11",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_12",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_13",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_14",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_15",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_16",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_17",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_18",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_19",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_20",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_21",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_22",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_23",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_24",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Mimikatz_LSASS_25",
        "malware_family": "Mimikatz_LSASS",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_1",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_2",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_3",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_4",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_5",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_6",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_7",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_8",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_9",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_10",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_11",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_12",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_13",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_14",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_15",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_16",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_17",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_18",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_19",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_20",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_21",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_22",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_23",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_24",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Emotet_Dropper_25",
        "malware_family": "Emotet_Dropper",
        "threat_category": "trojan",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_1",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_2",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_3",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_4",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_5",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_6",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_7",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_8",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_9",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_10",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_11",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_12",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_13",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_14",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_15",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_16",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_17",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_18",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_19",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_20",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_21",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_22",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_23",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_24",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "LockBit_Encryptor_25",
        "malware_family": "LockBit_Encryptor",
        "threat_category": "ransomware",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_1",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_2",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_3",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_4",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_5",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_6",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_7",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_8",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_9",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_10",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_11",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_12",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_13",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_14",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_15",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_16",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_17",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_18",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_19",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_20",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_21",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_22",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_23",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_24",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "ChinaChopper_Webshell_25",
        "malware_family": "ChinaChopper_Webshell",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_1",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_2",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_3",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_4",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_5",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_6",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_7",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_8",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_9",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_10",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_11",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_12",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_13",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_14",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_15",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_16",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_17",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_18",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_19",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_20",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_21",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_22",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_23",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_24",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Sliver_C2_25",
        "malware_family": "Sliver_C2",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_1",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_2",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_3",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_4",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_5",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_6",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_7",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_8",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_9",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_10",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_11",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_12",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_13",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_14",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_15",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_16",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_17",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_18",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_19",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_20",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_21",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_22",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_23",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_24",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "Metasploit_Meterpreter_25",
        "malware_family": "Metasploit_Meterpreter",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_1",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_2",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_3",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_4",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_5",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_6",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_7",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_8",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_9",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_10",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_11",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_12",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_13",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_14",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_15",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_16",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_17",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_18",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_19",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_20",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_21",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_22",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_23",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s3 = "eval($_POST["'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_24",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s1 = "sekurlsa::logonpasswords"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
    {
        "yara_rule_name": "AsyncRAT_Client_25",
        "malware_family": "AsyncRAT_Client",
        "threat_category": "c2_tool",
        "rule_strings": ['$s2 = "beacon.dll"'],
        "condition": "uint16(0) == 0x5A4D and any of ($s*)",
    },
]
